### ISSUE TITLE
Pursue doesn't actually finish when one of its branches finishes

### ISSUE THREAD

**Issue by mpomarlan** [cram2/cram_core#12]
Minimal example:

(cpl-impl:def-top-level-cram-function pursue-example () 
  (cpl-impl:pursue (progn (format t "Quick~%"))
                            (progn (sleep 2) (format t "Slow~%"))))

Expected behavior:
the program outputs "Quick" then terminates.

Reasons for expecting that behavior: 
  -- docstring of PURSUE:
     "Execute forms in parallel. Succeed if one succeeds, fail if one fails."
  -- docstring of cram-test pursue.1:
     "Make sure that PURSUE evaporates still-running childs if another child succeeds."

Actually observed behavior:
the program outputs "Quick", waits two seconds, outputs "Slow", then terminates.

**Comment by gaya-** [comment]
@mpomarlan  
Right, this is expected behavior. It's connected to the usage of sbcl's SLEEP, which does not respect CRAM's signalling system. If you use CPL:SLEEP instead, things should work fine.

**Comment by gaya-** [comment]
This is similar to https://github.com/cram-code/cram_core/issues/34, maybe you find the explanations useful.
