### ISSUE TITLE
Unable to catch designator-error with with-failure-handling

### ISSUE THREAD

**Issue by marcniehaus** [cram2/cram_core#2]
Hello CRAM team, 

I am operating on a scenario similar to the spatial_relations_demo. If I try to get an object-in-hand which is blocked by other objects (e.g. drawers) CRAM tries to get a pose for grasping but it is not able to sample one. Thus, a designator-error is thrown. However, I cannot directly catch this failure by using with-failure handling. Instead, the debugger is invoked. 
To reproduce the problem the following test code can be used:

`(cram-language:with-failure-handling`
`((cram-designators:designator-error (e)`
`(print "ERROR CAUGHT")`
`(return nil)))`
`(cram-plan-library:achieve`
`     `(cram-plan-library:object-in-hand `
`       ,(cram-designators:make-designator `
`         :object `
``((:type :mug) `
`         (:at ,(cram-designators:make-designator `
`                :location '((:on "Foo")(:name "Bar ")))))))))`

Before catching the failure, the debugger is invoked...

Kind regards,

Marc Niehaus

**Comment by gaya-** [comment]
I have been thinking about this and came to a conclusion that designator errors are low-level and should be handled by standard Lisp constructs like `handler-case`. And if the handler cannot solve the problem itself it should throw a plan failure, e.g., if a reachability designator cannot be resolved the handler should throw a `cram-plan-failure:manipulation-pose-unreachable` failure. Thus, this is a bug in the `cram_plan_library`, or rather a design flaw. I will keep this issue open until we fix the pick and place plan library. If the fixing will turn out too difficult I might reconsider my opinion that designator errors are low-level.

Thanks for the issue report.

**Comment by gaya-** [comment]
The newer plan libraries make sure to check if a designator can be resolved before using it in the plan execution. Therefore, I'm closing this issue, as it is a plan design issue and not a core CRAM library issue.
