### ISSUE TITLE
Generated locations always facing towards (0 0 0 1)

### ISSUE THREAD

**Issue by fairlight1337** [cram2/cram_core#4]
In the [Longterm Fetch and Place scenario](https://github.com/code-iai/longterm_fetch_and_place) I generate locations for a robot to see objects like this:
```lisp
(with-designators ((obj :object `((:at ,location))))
  (cram-plan-library:perceive-object 'cram-plan-library:all generic-object))
```
I call it like this:
```lisp
(top-level
  (with-process-modules
    (with-designators ((loc :location `((:on "CounterTop")
                                        (:name "http://knowrob.org/kb/IAI-kitchen.owl#iai_kitchen_kitchen_island_counter_top"))))
      (perceive-scene loc))))
```

While the location to stand at looks very good (and the robot drives there), its orientation is always towards `(0 0 0 1)`, meaning in positive `x` direction. The robot then turns its head to have a look at the actual objects.

Additionally to the default costmap generation, I restrict the allowed area using a predicates defined [here](https://github.com/code-iai/longterm_fetch_and_place/blob/master/ltfnp_executive/src/facts.lisp#L65) (see the link for implementation details):
```lisp
  (<- (desig-costmap ?desig ?cm)
    (or (desig-prop ?desig (:to :see))
        (desig-prop ?desig (:to :reach)))
    (costmap ?cm)
    (costmap-add-function scenario-area-restriction-distribution
                          (make-ltfnp-area-restriction-cost-function)
                          ?cm)))
```
I did not add an orientation generator to this. Also, I am [switching off](https://github.com/code-iai/longterm_fetch_and_place/pull/10/files#diff-5318b8412bcac04061f9df85b41d9d7aR168) some location validators as they prevent any locations to be generated for `(:to :see)`:
```lisp
(cram-designators:disable-location-validation-function 'btr-desig::check-ik-solution)
(cram-designators:disable-location-validation-function 'btr-desig::validate-designator-solution)
```
Any idea why this is happening, @gaya-? I haven't seen that behavior before. Should I add some kind of orientation generator to the predicate? Or is the `validate-designator-solution` validator actually taking care of this?

**Comment by gaya-** [comment]
(This is probably a cram_3d_world issue, as it is about the costmaps for visibility)

I would imagine that this behaviour is half-intended, you don't want to mess with navigation from the perception modules. You would usually want to approach counters parallel to them, not diagonally. However, I can see how this can be a problem when the counter is behind you. It does work for me in project mode, so I suspect that there are a number of orientations, probably 4, that are used. Was this behaviour always like that or is it a recent change?

**Comment by fairlight1337** [comment]
I had both, the deactivation of the validation functions, and the definition of the area restriction in place like this before (apart from changes in the actual restrictions, but that's just the x/y pairs allowed/forbidden). Also the `perceive-objects` plan was the same before. So I've seen this for the first time now.

I will dig out some old code to see whether I did something somewhere before that I now forgot, but I'm pretty sure about the above statements.

Odd, which part is actually generating the orientations? I remember something about a function that generates orientations towards a specific pose; maybe I'm overriding that somehow with the new predicate? I'll keep you posted about any news.

**Comment by fairlight1337** [comment]
Okay, I'm digging a bit deeper into this now. This is what I got so far.

I can reproduce the issue by manually generating the respective location designator:
```lisp
(with-designators ((loc-on-sink :location `((:on "CounterTop")
                                            (:name "iai_kitchen_sink_area_counter_top")))
                   (obj :object `((:at ,loc-on-sink)))
                   (loc-to-see :location `((:to :see) (:obj ,obj))))
  (cram-designators:reference loc-to-see))
```
And, after adding some output to `generate-orientations` (originally found in [location-costmap.lisp](https://github.com/cram2/cram_plans/blob/master/cram_location_costmap/src/location-costmap.lisp#L206)) like so:
```lisp
(defun generate-orientations (map x y
                              &optional (default (list (cl-transforms:make-identity-rotation))))
  (format t "Gen ori for ~a ~a: " x y)
  (let ((a (or (when (orientation-generators map)
                 (reduce (lambda (solution function)
                           (funcall function x y solution))
                         (orientation-generators map) :initial-value nil))
               default)))
    (format t "~a~%" a)
    a))
```
I'm getting this:
```lisp
Gen ori for 1.4000000953674316d0 0.34999990463256836d0: (#<QUATERNION
                                                           (0.0d0 0.0d0 0.0d0 1.0d0)>)
Gen ori for 0.7000002861022949d0 0.0d0: (#<QUATERNION
                                           (0.0d0 0.0d0 0.0d0 1.0d0)>)
Gen ori for 0.7000002861022949d0 0.40000009536743164d0: (#<QUATERNION
                                                           (0.0d0 0.0d0 0.0d0 1.0d0)>)
Gen ori for 0.5999999046325684d0 0.15000009536743164d0: (#<QUATERNION
                                                           (0.0d0 0.0d0 0.0d0 1.0d0)>)
Gen ori for 0.0d0 0.15000009536743164d0: (#<QUATERNION
                                            (0.0d0 0.0d0 0.0d0 1.0d0)>)
#<CL-TRANSFORMS-STAMPED:POSE-STAMPED 
   FRAME-ID: "map", STAMP: 0.0
   #<3D-VECTOR (0.0d0 0.15000009536743164d0 0.0d0)>
   #<QUATERNION (0.0d0 0.0d0 0.0d0 1.0d0)>>
```
So the orientation generators may be at fault here somehow. I'll look close and update the issue.

**Comment by fairlight1337** [comment]
After looking at the `map` parameter of `generate-orientations`, the glaring issue sprung to my eye:
```lisp
#<LOCATION-COSTMAP {1003008453}>
--------------------
Class: #<STANDARD-CLASS LOCATION-COSTMAP>
--------------------
 Group slots by inheritance [ ]
 Sort slots alphabetically  [X]

All Slots:
[ ]  COST-FUNCTIONS         = (#<FUNCTION-COSTMAP-GENERATOR {10199C8F63}> #<MAP-COSTMAP-GENERATOR {10199C8F83}> #<MAP-COSTMAP-GENERATOR {10199C8FA3}> #<MAP-COSTMAP-GENERATOR {10199C8FC3}> #<MAP-COSTMAP-GENERATOR {10199C8FE3}>)
[ ]  COST-MAP               = #2A((0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 0.0d0 ..)..
[ ]  HEIGHT                 = 10
[ ]  HEIGHT-GENERATORS      = (#<CLOSURE (LAMBDA # :IN CRAM-LOCATION-COSTMAP::MAKE-2D-VALUE-MAP-GENERATOR) {10199C900B}>)
[ ]  ORIENTATION-GENERATORS = NIL
[ ]  ORIGIN-X               = -5
[ ]  ORIGIN-Y               = -5
[ ]  RESOLUTION             = 0.05
[ ]  WIDTH                  = 10
```
`ORIENTATION-GENERATORS` is `nil` here. Maybe its related to no orientation generators being registered after all. I'll go on.

**Comment by fairlight1337** [comment]
Found it, but am in a meeting now. Will fix it when the meeting is over.

**Comment by fairlight1337** [comment]
Turns out the orientation generation related code now resides in the new repository `cram-robot-pose-gaussian-costmap` (the code was in `location-costmaps` before).

Adding a dependency on that package solved the orientation issues when resolving location designators. Maybe this should be centrally documented somewhere. I'll add a note to the longterm fetch and place scenario `README.md` once I find the time.

**Comment by gaya-** [comment]
Oh, I see, true, I forgot about that. I'll at least put it in the CRAM package spreadsheet for now. (https://docs.google.com/spreadsheets/d/1FTPf2HjlM18BMpSwd9GKimZCcmlNYAZLuQPkJAROVLg/edit#gid=0)
