### ISSUE TITLE
`with-desig-props` not working anymore with keywords as designator keys

### ISSUE THREAD

**Issue by fairlight1337** [cram2/cram_core#6]
The macro [`with-desig-props`](https://github.com/cram2/cram_core/blob/master/cram_designators/src/cram-designators/utils.lisp#L33) opens a lexical environment, binding a number of properties contained in a designator as local variables. The usage up to now looked like this:
```lisp
(with-desig-props (desig-props::name desig-props::type) designator
  (do-something-with desig-props::name desig-props::type))
```
Since the *key* part of the key/value pairs in designators now consists of keywords rather than symbols, they cannot be bound as variables anymore.

This:
```lisp
(desig:with-desig-props (:name :type) (make-designator :object `((:name a) (:type b)))
  :name)
```
Naturally fails with:
```lisp
Compile-time error:
  :NAME is a keyword, and cannot be used as a local variable.
```
One way to overcome this would be to bind the interned symbol-name of the key keyword:
```lisp
(let ((key (intern (symbol-name :key))))
  (do-something-with key))
```
What do you think? Would this be a good way?

I wanted to use `with-desig-props`, but will now work with `desig-prop-value` manually. Sadly I don't have the time to implement a fix right now.

@gaya- @airballking @mpomarlan @gheorghelisca

**Comment by gaya-** [comment]
This is not a bug of `cram_core` but a bug in your code that doesn't use the current functionality properly.

The usage of `with-desig-props` is now as following:

```lisp
(desig:with-desig-props (name type)
          (desig:make-designator :object `((:name :bla) (:type :blabla)))
        name)
```

where `name` and `type` are variable of the package that you're in.

**Comment by fairlight1337** [comment]
Is that documented somewhere? Because in the code it isn't.

**Comment by fairlight1337** [comment]
Ah, I see. So it doesn't change much, right? Before it said `desig-props::name`, so `desig-props::name` should still be bound properly. Alright, that solves that then.

**Comment by gaya-** [comment]
No, it isn't documented anywhere, please feel free to document it.

**Comment by fairlight1337** [comment]
Whenever there's time for that, I'll try to look into it.
